### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by JIzabal** [xiaoxia-xia/cse-15l-lab-report#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
  - Commands, java files, and other code should be written with backticks
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
  - Fix the last step so that the command runs the code on the remote server: Optimizing Remote Running (this is from the lab in week 1) - Write down in notes First try using just what we learned in this lab, and document the best process you came up with. Try to get the total time for a run after editing and saving to under 10 total keystrokes/mouse clicks, including all typing.
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by JIzabal** [comment]
We wanted you to make a local edit to WhereAmI.java, copy it to the remote server, and run it as described in the comment above. See the explanation below to see how to fix this:

We want you to copy the code from your computer to the remote server, compile the code that was copied onto the remote server, and then run the code that was compiled on the remote server. First, look into Part 5 of Lab 1 to see how to copy a file locally to the remote server using `scp`. Then, look into Part 7 of Lab 1 to see how to run commands (e.g., `javac` and `java`) on the remote server. There's an example of how to do this with `ls` but you need to do it for `javac` and `java`. Finally, see Part 7 of Lab 1 to figure out how to combine this all into one line through the use of semicolons. Let me know if you have any questions! Once you're done, go ahead and submit a regrade request.

**Comment by xiaoxia-xia** [comment]
hey friend, if I still did any wrong on this part, please let me know and I would correct it immediately. I wouldn't get an A if I failed to get credit on this one. That is very very important to me.
Thank you so much for your kindness

**Comment by JIzabal** [comment]
Hello! You need to switch your `scp` command so that it says `scp WhereAmI.java ieng6:~` based on how it's done [here](https://ucsd-cse15l-w22.github.io/week/week1/#part-5-moving-files-over-ssh-with-scp). Once you do that, message me here so I can check.

**Comment by xiaoxia-xia** [comment]
Thanks for letting me know! I think I corrected it now.

**Comment by JIzabal** [comment]
No problem! It looks like you forget to include the `javac` command in `ssh ieng6 "WhereAmI.java; java WhereAmI"` though.

**Comment by xiaoxia-xia** [comment]
I corrected it again, hope this time goona be well

**Comment by JIzabal** [comment]
Nice work!
